fizzbuzz課題の提出
YukiWatanabe824/ruby-practices pull request #1
Opened 2021-03-20 07:43 UTC by YukiWatanabe824

課題を提出します。
ご確認お願いします。

2021-03-23 04:39 UTC, komagata requested changes

2021-03-23 04:39 UTC, komagata commented on 01.fizzbuzz/fizzbuzz.rb
> +		if (num % 3)== 0 && (num % 5)== 0
rubyのインデントはスペース２個が一般的なのでそれに合わせるのがいいかもです〜

2021-03-23 12:31 UTC, YukiWatanabe824 commented on 01.fizzbuzz/fizzbuzz.rb
> +		if (num % 3)== 0 && (num % 5)== 0
確認ありがとうございます。
タブのインデントをスペース2個分にするものと勘違いしてました。
修正してもう一度プルリクエストを送ります。

2021-03-23 12:33 UTC, YukiWatanabe824 commented
インデントを修正しました。
再度ご確認お願いします。

2021-03-24 04:11 UTC, komagata commented on 01.fizzbuzz/fizzbuzz.rb
> +		if (num % 3)== 0 && (num % 5)== 0
プログラマーの間ではタブとスペースは厳密に違うのでタブのことを空間という意味でスペースと表現することはないので、その辺りを覚えておくとわかりやすいかもです〜

2021-03-24 04:12 UTC, komagata requested changes

2021-03-24 04:12 UTC, komagata commented on 01.fizzbuzz/fizzbuzz.rb
> +	}
ここのインデントのレベルが開始の行とあってないかもです〜

2021-03-24 12:08 UTC, YukiWatanabe824 commented on 01.fizzbuzz/fizzbuzz.rb
> +	}
改行したままのインデントを入れてました。詰めが甘かったです😭修正します！

2021-03-24 12:10 UTC, YukiWatanabe824 commented
｛｝のインデントを修正しました。
確認をお願いいたします。

2021-03-26 02:11 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-04-10 12:11 UTC, merged